export default [{Coffee: "El Salvador Aida Bottle", 
Method: "pour", 
Number_of_Cases: 10, 
Packets_per_Case: 10,
Ship_date: '11/1/11', 
Star: true, 
Order: "#12381"},

{Coffee: "El Salvador Aida Bottle", 
Method: "pour", 
Number_of_Cases: 10, 
Packets_per_Case: 10,
Ship_date: '11/1/11', 
Star: true, 
Order: "#12381"},
{Coffee: "El Salvador Aida Bottle", 
Method: "pour", 
Number_of_Cases: 10, 
Packets_per_Case: 10,
Ship_date: '11/1/11', 
Star: true, 
Order: "#12381"},
{Coffee: "El Salvador Aida Bottle", 
Method: "pour", 
Number_of_Cases: 10, 
Packets_per_Case: 10,
Ship_date: '11/1/11', 
Star: true, 
Order: "#12381"},
{Coffee: "El Salvador Aida Bottle", 
Method: "pour", 
Number_of_Cases: 10, 
Packets_per_Case: 10,
Ship_date: '11/1/11', 
Star: true, 
Order: "#12381"}]